name: Update Campaigns Data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1440

      - name: Fetch Campaigns Data
        id: fetch_campaigns
        run: |
          curl -sS -X GET -H "X-Super-Client: gh-actions-ashortsleeves" -o campaigns.json https://api.helldivers2.dev/api/v1/campaigns
          sleep 2
          curl -sS -X GET -H "X-Super-Client: gh-actions-ashortsleeves" -o assignments.json https://api.helldivers2.dev/api/v1/assignments
          sleep 2
          curl -sS -X GET -H "X-Super-Client: gh-actions-ashortsleeves" -o newsfeed.json https://api.helldivers2.dev/raw/api/NewsFeed/801
          sleep 2
          curl -sS -X GET -H "X-Super-Client: gh-actions-ashortsleeves" -o dispatches.json https://api.helldivers2.dev/api/v1/dispatches
          sleep 2
          curl -sS -X GET -H "X-Super-Client: gh-actions-ashortsleeves" -o space-stations.json https://api.helldivers2.dev/api/v1/space-stations

      - name: Check if JSON files are empty
        id: check_empty
        run: |
          if [ ! -s "campaigns.json" ] || [ ! -s "assignments.json" ] || [ ! -s "newsfeed.json" ] || [ ! -s "dispatches.json" ] || [ ! -s "space-stations.json" ]; then
            echo "One or more JSON files are empty."
            echo "::set-output name=empty::true"
          else
            echo "All JSON files are non-empty."
            echo "::set-output name=empty::false"
          fi

      - name: Commit and push if it changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add campaigns.json
          git add assignments.json
          git add newsfeed.json
          git add dispatches.json
          git add space-stations.json
          timestamp=$(TZ="America/New_York" date +"%Y-%m-%d %I:%M:%S %p")
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
