name: Update Campaigns Data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '*/10 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 1440

    - name: Fetch Campaigns Data
      id: fetch_campaigns
      run: |
        curl -sS -X GET -H "X-Super-Client: gh-actions-ashortsleeves" -H "X-Super-Contact: gh/ashortsleeves" -o campaigns.json https://api.helldivers2.dev/api/v1/campaigns
        sleep 2
        curl -sS -X GET -H "X-Super-Client: gh-actions-ashortsleeves" -H "X-Super-Contact: gh/ashortsleeves" -o assignments.json https://api.helldivers2.dev/api/v1/assignments
        sleep 2
        curl -sS -X GET -H "X-Super-Client: gh-actions-ashortsleeves" -H "X-Super-Contact: gh/ashortsleeves" -o newsfeed.json https://api.helldivers2.dev/raw/api/NewsFeed/801
        sleep 2
        curl -sS -X GET -H "X-Super-Client: gh-actions-ashortsleeves" -H "X-Super-Contact: gh/ashortsleeves" -o dispatches.json https://api.helldivers2.dev/api/v1/dispatches
        sleep 2
        curl -sS -X GET -H "X-Super-Client: gh-actions-ashortsleeves" -H "X-Super-Contact: gh/ashortsleeves" -o space-stations.json https://api.helldivers2.dev/api/v1/space-stations

    - name: Check if JSON files are valid and non-empty
      id: check_valid
      run: |
        validate_json() {
          file=$1
          if [ ! -s "$file" ]; then
            echo "$file is empty."
            return 1
          fi
          if ! jq empty "$file" >/dev/null 2>&1; then
            echo "$file is not valid JSON."
            return 1
          fi
          return 0
        }
        all_valid=true
        for f in campaigns.json assignments.json newsfeed.json dispatches.json space-stations.json; do
          if ! validate_json "$f"; then
            all_valid=false
          fi
        done

        if [ "$all_valid" = false ]; then
          echo "One or more files are empty or invalid."
          echo "valid=false" >> $GITHUB_OUTPUT
        else
          echo "All files are valid."
          echo "valid=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push if it changed
      if: steps.check_valid.outputs.valid == 'true'
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add campaigns.json assignments.json newsfeed.json dispatches.json space-stations.json
        timestamp=$(TZ="America/New_York" date +"%Y-%m-%d %I:%M:%S %p")
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
