name: Update Campaigns Data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 1440

    - name: Fetch Campaigns Data
      run: |-
        curl -X GET \
          -H "X-Super-Client: Heckdivers" \
          -H "X-Super-Contact: gh/ashortsleeves" \
          -o campaigns.json.tmp \
          https://api.helldivers2.dev/api/v1/campaigns || exit 0
        curl -X GET \
          -H "X-Super-Client: Heckdivers" \
          -H "X-Super-Contact: gh/ashortsleeves" \
          -o assignments.json.tmp \
          https://api.helldivers2.dev/api/v1/assignments || exit 0
        curl -X GET \
          -H "X-Super-Client: Heckdivers" \
          -H "X-Super-Contact: gh/ashortsleeves" \
          -o newsfeed.json.tmp \
          https://api.helldivers2.dev/raw/api/NewsFeed/801 || exit 0

    - name: Commit and push if data fetched
      run: |-
        if [ -e "campaigns.json.tmp" ]; then
          mv campaigns.json.tmp campaigns.json
          git add campaigns.json
        fi
        if [ -e "assignments.json.tmp" ]; then
          mv assignments.json.tmp assignments.json
          git add assignments.json
        fi
        if [ -e "newsfeed.json.tmp" ]; then
          mv newsfeed.json.tmp newsfeed.json
          git add newsfeed.json
        fi

        if [ -n "$(git status --porcelain)" ]; then
          timestamp=$(date -u)
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git commit -m "Latest data: ${timestamp}"
          git push
        else
          echo "No changes to commit"
        fi
